---
- name: apply common configuration to all nodes
  hosts: botman
  sudo: True
  roles:
    - common
    #- app
  vars:
    servername: botman 
    timezone:   Asia/Shanghai

  vars_files:
    - vars/common.yml

- name: install jenkins jenkins-debian-glue
  hosts: botman
  sudo: True
  roles:
    - jenkins

- name: configure and deploy the webservers and application code
  hosts: webservers
  sudo: True

  roles:
    - web

- name: deploy MySQL and configure the databases
  hosts: dbservers
  #remote_user: ubuntu
  sudo: True
  roles:
    - db

- name: deploy jenkins slave build machine
  hosts: jenkins_slave_p1

  sudo: True

  roles:
    - jenkins_slave
